openapi: 3.0.3
info: 
  title: Soundlabs API
  description: Event and DJ API for soundlabs rmc vienna
  version: "0.1"

servers:
  - url: http://localhost:9000
  - url: http://the.real.url/
  
paths:
  /events:
    get:
      summary: Returns a list of events.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: Returns a list of events.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#/components/schemas/Event"
      tags: 
        - Events
  /events/{eventsId}:
    get:
      responses:
        '200':    # status code
          description: Returns a single event.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#/components/schemas/Event"
      tags: 
        - Events
    put:
      responses:
        '200':
          description: Creates an event.
          content:
            application/json:
              schema: 
                type: object
                items: 
                  $ref: "#/components/schemas/Event"
    #delete:
    #  responses:
    #    '200':    
    #      content:
          
  /djs:
    get:
      parameters:
        - in: query
          name: eventsId
          schema:
            type: string
      summary: Returns a list of DJs.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: Returns a list of djs or a specific dj.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#/components/schemas/DJ"
        '404':
          description: Not Found
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#/components/schemas/NotFoundError"
      tags: 
        - DJs
    post:
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              items: 
                $ref: "#/components/schemas/DJ"
      responses:
        '200':    # status code
          description: Created
        '400':
          description: Bad Request
      tags: 
        - DJs
components:
  schemas:
    CreationError: 
      type: object
      properties:
          errorMessage: 
            type: string
            example: "Validation Error. Author with name already exists"
    NotFoundError: 
      type: object
      properties:
          errorMessage: 
            type: string
            example: "Content not found"
    Event: 
      type: object
      properties:
          id:
            type: integer
            format: int64
            example: 12345
          name: 
            type: string
            example: "Resselrave"
    DJ:
      type: object
      properties:
        id: 
          type: integer
          format: int64
          example: 12345
        name: 
          type: string
          example: "Dj McDJFace"



tags:
  - name: Events
  - name: DJs
  - name: Hosts
  - name: Locations
